use super::types::*;
use anyhow::Result;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};
use tokio::sync::RwLock;

/// Source of a dynamic rule
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RuleSource {
    Static,      // From rules.json files
    UserConsent, // From consent approval
    System,      // Generated by system
}

/// Dynamic rule with metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DynamicRule {
    pub rule: RuleDefinition,
    pub source: RuleSource,
    pub created_at: u64,
    pub created_by: String, // Wallet address
    pub use_count: u32,
    pub use_count_limit: Option<u32>,
    pub expires_at: Option<u64>,
    pub recurring: bool,
}

impl DynamicRule {
    /// Check if rule has expired
    pub fn is_expired(&self) -> bool {
        if let Some(expires_at) = self.expires_at {
            let now = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_secs();
            return now > expires_at;
        }
        false
    }

    /// Check if rule has reached use count limit
    pub fn is_exhausted(&self) -> bool {
        if let Some(limit) = self.use_count_limit {
            return self.use_count >= limit;
        }
        false
    }

    /// Check if rule is still valid
    pub fn is_valid(&self) -> bool {
        !self.is_expired() && !self.is_exhausted()
    }

    /// Increment use count
    pub fn increment_use_count(&mut self) {
        self.use_count += 1;
    }
}

/// Store for dynamic rules with optional Redis backend
pub struct DynamicRuleStore {
    /// In-memory cache of rules
    local_cache: Arc<RwLock<HashMap<String, DynamicRule>>>,
    /// Optional Redis URL for multi-instance sync
    redis_url: Option<String>,
    /// Cache TTL in seconds
    cache_ttl: u64,
}

impl DynamicRuleStore {
    /// Create a new dynamic rule store
    pub fn new(redis_url: Option<String>) -> Self {
        Self {
            local_cache: Arc::new(RwLock::new(HashMap::new())),
            redis_url,
            cache_ttl: 10, // 10 second cache
        }
    }

    /// Add a rule to the store
    pub async fn add_rule(&self, rule: DynamicRule) -> Result<()> {
        let rule_id = rule.rule.id.clone();

        // Store in local cache
        {
            let mut cache = self.local_cache.write().await;
            cache.insert(rule_id.clone(), rule.clone());
        }

        // Store in Redis if configured
        if let Some(redis_url) = &self.redis_url {
            self.store_in_redis(redis_url, &rule).await?;
        }

        log::info!("✅ Dynamic rule added: {}", rule_id);
        Ok(())
    }

    /// Remove a rule from the store
    pub async fn remove_rule(&self, rule_id: &str) -> Result<()> {
        // Remove from local cache
        {
            let mut cache = self.local_cache.write().await;
            cache.remove(rule_id);
        }

        // Remove from Redis if configured
        if let Some(redis_url) = &self.redis_url {
            self.remove_from_redis(redis_url, rule_id).await?;
        }

        log::info!("🗑️  Dynamic rule removed: {}", rule_id);
        Ok(())
    }

    /// Get all valid rules from the store
    pub async fn get_all_rules(&self) -> Vec<DynamicRule> {
        log::trace!(
            "DynamicRuleStore::get_all_rules (cache_ttl_sec={})",
            self.cache_ttl
        );
        // Refresh from Redis if configured and cache is stale
        if self.redis_url.is_some() {
            if let Err(e) = self.refresh_from_redis().await {
                log::warn!("Failed to refresh rules from Redis: {}", e);
            }
        }

        let cache = self.local_cache.read().await;
        cache.values().filter(|r| r.is_valid()).cloned().collect()
    }

    /// Get rules matching a transaction (by canonical hash or other conditions)
    pub async fn get_matching_rules(&self, canonical_hash: Option<&str>) -> Vec<DynamicRule> {
        let all_rules = self.get_all_rules().await;

        all_rules
            .into_iter()
            .filter(|rule| {
                // Check if rule matches canonical hash
                if let Some(hash) = canonical_hash {
                    if let Some(rule_hash) = rule.rule.metadata.get("canonical_transaction_hash") {
                        if let Some(rule_hash_str) = rule_hash.as_str() {
                            if rule_hash_str == hash {
                                return true;
                            }
                        }
                    }
                }

                // For now, return all valid rules
                // TODO: Add more sophisticated matching logic
                true
            })
            .collect()
    }

    /// Increment use count for a rule
    pub async fn increment_use_count(&self, rule_id: &str) -> Result<()> {
        let mut cache = self.local_cache.write().await;

        if let Some(rule) = cache.get_mut(rule_id) {
            rule.increment_use_count();

            // Check if rule is exhausted
            if rule.is_exhausted() {
                log::info!("🏁 Rule {} has reached use limit, removing", rule_id);
                drop(cache); // Release lock before calling remove_rule
                self.remove_rule(rule_id).await?;
            }
        }

        Ok(())
    }

    /// Clean up expired rules
    pub async fn cleanup_expired(&self) -> Result<()> {
        let expired_ids: Vec<String> = {
            let cache = self.local_cache.read().await;
            cache
                .iter()
                .filter(|(_, rule)| rule.is_expired())
                .map(|(id, _)| id.clone())
                .collect()
        };

        for rule_id in expired_ids {
            self.remove_rule(&rule_id).await?;
        }

        Ok(())
    }

    /// Store rule in Redis
    #[cfg(feature = "dynamic-rules")]
    async fn store_in_redis(&self, redis_url: &str, rule: &DynamicRule) -> Result<()> {
        let client = redis::Client::open(redis_url)?;
        let mut conn = client.get_multiplexed_async_connection().await?;

        let key = format!("dynamic_rules:{}", rule.rule.id);
        let value = serde_json::to_string(rule)?;

        use redis::AsyncCommands;

        if let Some(expires_at) = rule.expires_at {
            let now = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_secs();
            let ttl = expires_at.saturating_sub(now);

            conn.set_ex::<_, _, ()>(&key, &value, ttl).await?;
        } else {
            conn.set::<_, _, ()>(&key, &value).await?;
        }

        // Publish event for cache invalidation
        conn.publish::<_, _, ()>("dynamic_rules:updated", &rule.rule.id)
            .await?;

        Ok(())
    }

    #[cfg(not(feature = "dynamic-rules"))]
    async fn store_in_redis(&self, _redis_url: &str, _rule: &DynamicRule) -> Result<()> {
        log::warn!("Redis support not enabled, dynamic rule will only be stored in memory");
        Ok(())
    }

    /// Remove rule from Redis
    #[cfg(feature = "dynamic-rules")]
    async fn remove_from_redis(&self, redis_url: &str, rule_id: &str) -> Result<()> {
        let client = redis::Client::open(redis_url)?;
        let mut conn = client.get_multiplexed_async_connection().await?;

        let key = format!("dynamic_rules:{}", rule_id);

        use redis::AsyncCommands;
        conn.del::<_, ()>(&key).await?;

        // Publish event
        conn.publish::<_, _, ()>("dynamic_rules:deleted", rule_id)
            .await?;

        Ok(())
    }

    #[cfg(not(feature = "dynamic-rules"))]
    async fn remove_from_redis(&self, _redis_url: &str, _rule_id: &str) -> Result<()> {
        Ok(())
    }

    /// Refresh local cache from Redis
    #[cfg(feature = "dynamic-rules")]
    async fn refresh_from_redis(&self) -> Result<()> {
        if let Some(redis_url) = &self.redis_url {
            let client = redis::Client::open(redis_url.as_str())?;
            let mut conn = client.get_multiplexed_async_connection().await?;

            use redis::AsyncCommands;

            // Get all dynamic rule keys
            let keys: Vec<String> = conn.keys("dynamic_rules:*").await?;

            let mut new_cache = HashMap::new();

            for key in keys {
                let value: String = conn.get(&key).await?;
                if let Ok(rule) = serde_json::from_str::<DynamicRule>(&value) {
                    new_cache.insert(rule.rule.id.clone(), rule);
                }
            }

            // Update local cache
            let mut cache = self.local_cache.write().await;
            *cache = new_cache;

            log::debug!("🔄 Refreshed {} rules from Redis", cache.len());
        }

        Ok(())
    }

    #[cfg(not(feature = "dynamic-rules"))]
    async fn refresh_from_redis(&self) -> Result<()> {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dynamic_rule_expiry() {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();

        let mut rule = DynamicRule {
            rule: RuleDefinition {
                version: "1.0".to_string(),
                id: "test".to_string(),
                name: "Test".to_string(),
                description: None,
                author: None,
                enabled: true,
                tags: vec![],
                rule: Rule {
                    action: RuleAction::Pass,
                    conditions: RuleCondition::Simple(SimpleCondition {
                        field: "test".to_string(),
                        operator: ComparisonOperator::Equals,
                        value: serde_json::json!("test"),
                    }),
                    message: "Test".to_string(),
                    flowstate: None,
                },
                metadata: HashMap::new(),
            },
            source: RuleSource::System,
            created_at: now,
            created_by: "test".to_string(),
            use_count: 0,
            use_count_limit: Some(5),
            expires_at: Some(now + 60),
            recurring: false,
        };

        // Should be valid
        assert!(rule.is_valid());

        // Increment use count
        for _ in 0..5 {
            rule.increment_use_count();
        }

        // Should be exhausted
        assert!(rule.is_exhausted());
        assert!(!rule.is_valid());
    }
}
